project:
  type: book

book:
  title: "Mastering Shiny Examples and Solutions for Python"
  author: "Youngrok Lee"
  date: today
  chapters:
    - index.qmd
    - part: "Getting Started"
      chapters:
      - basic-app.qmd
      - basic-ui.qmd
      - basic-reactivity.qmd
      - basic-case-study.qmd
    - part: "Shiny in Action"
      chapters:
      - action-workflow.qmd
      - action-layout.qmd
      - action-graphics.qmd
      - action-feedback.qmd
      - action-transfer.qmd
      - action-dynamic.qmd
  repo-url: https://github.com/youngroklee-ml/mastering-shiny-for-python
  repo-actions: [edit, issue]

number-sections: false

format:
  html:
    theme: cosmo

execute: 
  freeze: auto

