project:
  type: book

book:
  title: "Mastering Shiny Examples and Solutions for Python"
  author: "Youngrok Lee"
  date: today
  chapters:
    - index.qmd
    - part: "Getting Started"
      - basic-app.qmd
      - basic-ui.qmd
      - basic-reactivity.qmd
      - basic-case-study.qmd
    - part: "Shiny in Action"
  repo-url: https://github.com/youngroklee-ml/mastering-shiny-for-python
  repo-actions: [edit, issue]

number-sections: false

format:
  html:
    theme: cosmo

execute: 
  freeze: auto

