project:
  type: book

book:
  title: "Mastering Shiny Examples and Solutions for Python"
  author: "Youngrok Lee"
  date: today
  chapters:
    - index.qmd
    - basic-app.qmd
    - basic-ui.qmd

number-sections: false

format:
  html:
    theme: cosmo



